### ISSUE TITLE
Project state? Fork!

### ISSUE THREAD

**Issue by f4bio** [qdot/systray-rs#33]
hi.

No idea what @qdot 's plans for this crate is, but it seems kinda abandoned?!
So I've decided to fork it and try to continue working on it: [gitlab:f4bio/systray-rs](https://gitlab.com/f4bio/systray-rs)

I've merged #22, #32, #33, bumped crate version to 0.3.1, updated dependencies, added a working somewhat working windows example, started an macos example recently as well as integration and unit tests. also added `CHANGELOG`, `.gitlab-ci.yml` and other boilerplate things...
most of the more recent changes are wip! (my commits will be on feature branches from here on out, I guess...)

I'm just getting into rust - in fact, I'm using this crate in my first ever rust project! :)

Feedback and/or PRs are of course always welcome! 

Also, no freaking idea what to do with the original license? I've just slapped "my" (the default one) MIT license on it, no idea if thats "allowed" or even ... legal? 🤔 

I hope I didn't forget to mention anything?!

best,
Fabio

**Comment by qdot** [comment]
Hello! And welcome to the special hell that is open source project ownership!

So first off, I'd already posted an issue asking for help: https://github.com/qdot/systray-rs/issues/25. I suppose forking works too, as yes, I have definitely abandoned the project.

Forking is difficult because I'm still the owner of the crates.io package, so a clean handoff would also require transmission of that ownership somehow. I'm not particularly sure how that works with crates.io.

Also, just because you forked systray-rs doesn't mean you've got everything. libappindicator and libappindicator-sys will also need to be maintained if you want this to work on linux, unless you are planning on shifting how task tray icon rendering works.

For licensing, you cannot pull my license off the code, as I have signed no CLA relinquishing my rights to the code. Not only that, you left my license in the README and put yours in the LICENSE.txt, which is incorrect anyways. The way this works is that you will now have a compound license. You would include my original license in the LICENSE.txt and README, then yours on top of it. The update of the copyright on the license denotes the time of ownership. Please update to this immediately.

While I understand you're excited and have good intentions, next time, please try asking before forking and announcing. You can see from my profile that I'm quite active on github, just not on this particular project. I would've been happy to explain this and possibly direct you beforehand.

**Comment by f4bio** [comment]
thanks for answering so quickly!

Initially, it wasn't really my intention to make any move in the direction of me continuing this lib by myself... But, since I really liked your approach on this, my being able to develop (or maybe "run" in this regards) on all 3 OSes simultaneously and you seem to have left this project hanging in the waters (if thats even an expression?! 😄) - my conclusion was to go ahead myself. 
The alternative, an abundant, slowly dying lib doesn't sound so good and wouldn't give it enough justice.

Alright, enough poetics...
The licensing, #25 as well as this issue, would be solved by merging pending and upcoming PRs, you're totally right of course. 
So, if I understood everything correctly, we may should continue discussion over there and kill this issue (sorry for confusion etc)
